import type { Player } from "./models"

export const players: Player[] = [
  { place: 1, score: 200000,
    username: 'PavMash',
    status: 'online', is_me: false },
  { place: 2, score: 100000,
    username: 'Stepan_Tap',
    status: 'online', is_me: true },
  { place: 3, score: 5000,
    username: 'al.blinov',
    status: 'offline', is_me: false },
  { place: 3, score: 5000,
    username: 'al.blinov',
    status: 'offline', is_me: false },
  { place: 3, score: 5000,
    username: 'al.blinov',
    status: 'offline', is_me: false },
  { place: 3, score: 5000,
    username: 'al.blinov',
    status: 'offline', is_me: false },
  { place: 3, score: 5000,
    username: 'al.blinov',
    status: 'offline', is_me: false },
  { place: 3, score: 5000,
    username: 'al.blinov',
    status: 'offline', is_me: false },
  { place: 3, score: 5000,
    username: 'al.blinov',
    status: 'offline', is_me: false },
  { place: 3, score: 5000,
    username: 'al.blinov',
    status: 'offline', is_me: false },
  { place: 3, score: 5000,
    username: 'al.blinov',
    status: 'offline', is_me: false },
  { place: 3, score: 5000,
    username: 'al.blinov',
    status: 'offline', is_me: false },
  { place: 3, score: 5000,
    username: 'al.blinov',
    status: 'offline', is_me: false },
  { place: 3, score: 5000,
    username: 'al.blinov',
    status: 'offline', is_me: false },
  { place: 3, score: 5000,
    username: 'al.blinov',
    status: 'offline', is_me: false },
  { place: 3, score: 5000,
    username: 'al.blinov',
    status: 'offline', is_me: false },
  { place: 3, score: 5000,
    username: 'al.blinov',
    status: 'offline', is_me: false },
  { place: 3, score: 5000,
    username: 'al.blinov',
    status: 'offline', is_me: false },
  { place: 3, score: 5000,
    username: 'al.blinov',
    status: 'offline', is_me: false },
  { place: 3, score: 5000,
    username: 'al.blinov',
    status: 'offline', is_me: false },
  { place: 3, score: 5000,
    username: 'al.blinov',
    status: 'offline', is_me: false },
  { place: 3, score: 5000,
    username: 'al.blinov',
    status: 'offline', is_me: false },
  { place: 3, score: 5000,
    username: 'al.blinov',
    status: 'offline', is_me: false },
  { place: 3, score: 5000,
    username: 'al.blinov',
    status: 'offline', is_me: false },
  { place: 3, score: 5000,
    username: 'al.blinov',
    status: 'offline', is_me: false },
  { place: 3, score: 5000,
    username: 'al.blinov',
    status: 'offline', is_me: false },
  { place: 3, score: 5000,
    username: 'al.blinov',
    status: 'offline', is_me: false },
]
