name: Docker Compose Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  docker-compose-up:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up environment variables
        run: |
          echo "${{ secrets.ENV_FILE64 }}" | base64 -d -i > .env
          cd auth
          mkdir secrets
          echo "${{ secrets.PUBLIC_JWT}}" | base64 -d -i > secrets/jwt_public.pem
          echo "${{ secrets.PRIVATE_JWT}}" | base64 -d -i > secrets/jwt_private.pem
          cd ..
          cd lobby
          echo "${{ secrets.PUBLIC_JWT}}" | base64 -d -i > jwt_public.pem

      - name: Docker Compose up
        run: |
          docker compose up -d
          sleep 10
          docker compose ps
          docker compose logs

      - name: Docker Compose down
        if: always()
        run: docker compose down
